#!/bin/sh

# Prevent the push if the linting fails, but only if you are not on the batchfarm since there docker is not available
[[ "$(lsb_release -i | awk '{print $3}')" != "AlmaLinux" ]]  && exec yaffa-lint
