# Generator setup
nevts: 1000
sqrts: 13 # um = TeV
tune: CRMode2
process: NonDiffractive
trigger: MB # todo: not implemented

# Selection of particle 0
part0: # Put here the heaviest of the two particles
    pdg: 2212
    status: [81, 89] # NB: extremes are included
    y: null
    eta: [-2, 2]
    pt: null
    prodvtx: [-1, 0.5] # um = mm
    dauintpc: true

# Selection of particle 1
part1: null # Use null if same as part 1
    # pdg: 211
    # status: [81, 89] # NB: extremes are included. Negative values if the particle decays
    # y: null
    # eta: [-2, 2]
    # pt: null
    # prodvtx: [-1, 0.5] # Don't use 0 as lower value
    # dauintpc: true

# Femtoscopy
mixdepth: 10
rejevtwopairs: true
# todo: implement rejection of events without pairs
