# Generator setup
nevts: 3000
sqrts: 13 # um = TeV
tune: CRMode2
process: NonDiffractive
trigger: MB # todo: not implemented

# Selection of particle 0
part0: # Put here the heaviest of the two particles
    pdg: 211
    status: [81, 89] # NB: extremes are included
    y: null
    eta: [-0.8, 0.8]
    pt: [0, 999]
    prodvtx: [-1, 0.5]
    

# Selection of particle 1
part1: # Use null if same as part 1
    pdg: 333
    status: [-89, -81] # NB: extremes are included. Negative values if the particle decays
    y: null
    eta: null
    pt: null
    prodvtx: [-1, 0.5] # Don't use 0 as lower value

# Femtoscopy
mixdepth: 10
# todo: implement rejection of events without pairs
