/*
Script to compute the same- and mixed event distributions from pythia events.
*/

// C++ libraries
#include <map>
#include <string>
#include <vector>

// ROOT libraries
#include "Riostream.h"
#include "TFile.h"
#include "TH1.h"
#include "TRandom3.h"

// ALICE libraries
#include "Pythia8/Pythia.h"


bool IsInAcc(Pythia8::Particle part, const Pythia8::Pythia &pythia, double maxEtaTrk) {
    if (std::abs(part.id()) == 421 || std::abs(part.id()) == 411) { // D0 and D+
        for (const int &dau : part.daughterList()) if (std::abs(pythia.event[dau].eta()) > maxEtaTrk) return false;
        return true;
    } else if (std::abs(part.id()) == 413) { // D*+(2010)
        Pythia8::Particle d1, d2, pion, Dzero;
        d1 = pythia.event[part.daughter1()];
        d2 = pythia.event[part.daughter2()];
        if (std::abs(d1.id()) == 421) {
            Dzero=d1;
            pion=d2;
        } else {
            Dzero=d2;
            pion=d1;
        }

        return std::abs(pion.eta()) < maxEtaTrk && IsInAcc(Dzero, pythia, maxEtaTrk);
    } else {
        printf("Decay of particle %d is not implemented. Exit!\n", part.id());
        exit(1);
    }
    return true;
}


void DmesonKinem(
    long unsigned int nEvents = 10000,
    int pdg = 421,
    std::string oFileName = "../../secrets/alice3/KinemDzero.root",
    int seed = 31
    ) {
    Pythia8::Pythia pythia;

    // Set process
    pythia.readString("HardQCD:hardccbar = on");
    pythia.readString("HardQCD:hardbbbar = on");

    // Force decays
    pythia.readString("421:onMode = off");
    pythia.readString("411:onMode = off");
    pythia.readString("413:onMode = off");
    pythia.readString("421:onIfMatch = 211 321");
    pythia.readString("411:onIfMatch = 211 211 321");
    pythia.readString("413:onIfMatch = 211 421");

    // Set tune
    pythia.readString(Form("Tune:pp = 14"));
    pythia.readString("ColourReconnection:mode = 1");
    pythia.readString("ColourReconnection:allowDoubleJunRem = off");
    pythia.readString("ColourReconnection:m0 = 0.3");
    pythia.readString("ColourReconnection:allowJunctions = on");
    pythia.readString("ColourReconnection:junctionCorrection = 1.20");
    pythia.readString("ColourReconnection:timeDilationMode = 2");
    pythia.readString("ColourReconnection:timeDilationPar = 0.18");
    pythia.readString("StringPT:sigma = 0.335");
    pythia.readString("StringZ:aLund = 0.36");
    pythia.readString("StringZ:bLund = 0.56");
    pythia.readString("StringFlav:probQQtoQ = 0.078");
    pythia.readString("StringFlav:ProbStoUD = 0.2");
    pythia.readString("StringFlav:probQQ1toQQ0join = 0.0275,0.0275,0.0275,0.0275");
    pythia.readString("MultiPartonInteractions:pT0Ref = 2.15");
    pythia.readString("BeamRemnants:remnantMode = 1");
    pythia.readString("BeamRemnants:saturation = 5");

    // Setting the seed here is not sufficient to ensure reproducibility, setting the seed of gRandom is necessary
    pythia.readString("Random:setSeed = on");
    pythia.readString(Form("Random:seed = %d", seed));
    pythia.settings.mode("Beams:idA", 2212);
    pythia.settings.mode("Beams:idB", 2212);
    pythia.settings.parm("Beams:eCM", 14000); // from TeV to GeV
    pythia.init();

    gRandom->SetSeed(seed); // Set the seed to ensure reproducibility of the evevents generated by pythia

    TH1D *hY = new TH1D("hY", ";#it{y};Counts", 100, -4.5, 4.5);
    TH1D *hPt = new TH1D("hPt", ";#it{p}_{T};Counts", 100, 0, 10);
    
    for (size_t iEvent = 0; iEvent < nEvents; iEvent++) {
        pythia.next();

        // Part 0 is the event, 1 and 2 the beams ==> start from 3
        for (int iPart = 3; iPart < pythia.event.size(); iPart++) {
            auto &part = pythia.event[iPart];

            if (std::abs(part.id()) == pdg) {
                hY->Fill(part.y());
                hPt->Fill(part.pT());
            }
        }
    }

    TFile *oFile = new TFile(oFileName.data(), "recreate");
    hY->Write();
    hPt->Write();
    oFile->Close();
}
