/*
Script to compute the same- and mixed event distributions from pythia events.
*/

// C++ libraries
#include <map>
#include <string>
#include <vector>

// ROOT libraries
#include "Riostream.h"
#include "TFile.h"
#include "TH1.h"
#include "TRandom3.h"

// ALICE libraries
#include "Pythia8/Pythia.h"


bool IsInAcc(Pythia8::Particle part, const Pythia8::Pythia &pythia, double maxEtaTrk) {
    if (std::abs(part.id()) == 421 || std::abs(part.id()) == 411) { // D0 and D+
        for (const int &dau : part.daughterList()) if (std::abs(pythia.event[dau].eta()) > maxEtaTrk) return false;
        return true;
    } else if (std::abs(part.id()) == 413) { // D*+(2010)
        Pythia8::Particle d1, d2, pion, Dzero;
        d1 = pythia.event[part.daughter1()];
        d2 = pythia.event[part.daughter2()];
        if (std::abs(d1.id()) == 421) {
            Dzero=d1;
            pion=d2;
        } else {
            Dzero=d2;
            pion=d1;
        }

        return std::abs(pion.eta()) < maxEtaTrk && IsInAcc(Dzero, pythia, maxEtaTrk);
    } else {
        printf("Decay of particle %d is not implemented. Exit!\n", part.id());
        exit(1);
    }
    return true;
}


void EstimateDmesonAccALICE3(
    long unsigned int nEvents = 10000,
    int pdg = 421,
    std::string oFileName = "../../secrets/alice3/DmesonAccALICE3.root",
    int seed = 31
    ) {
    Pythia8::Pythia pythia;

    // Set process
    pythia.readString("HardQCD:hardccbar = on");
    pythia.readString("HardQCD:hardbbbar = on");

    // Force decays
    pythia.readString("421:onMode = off");
    pythia.readString("411:onMode = off");
    pythia.readString("413:onMode = off");
    pythia.readString("421:onIfMatch = 211 321");
    pythia.readString("411:onIfMatch = 211 211 321");
    pythia.readString("413:onIfMatch = 211 421");

    // Set tune
    pythia.readString(Form("Tune:pp = 14"));
    pythia.readString("ColourReconnection:mode = 1");
    pythia.readString("ColourReconnection:allowDoubleJunRem = off");
    pythia.readString("ColourReconnection:m0 = 0.3");
    pythia.readString("ColourReconnection:allowJunctions = on");
    pythia.readString("ColourReconnection:junctionCorrection = 1.20");
    pythia.readString("ColourReconnection:timeDilationMode = 2");
    pythia.readString("ColourReconnection:timeDilationPar = 0.18");
    pythia.readString("StringPT:sigma = 0.335");
    pythia.readString("StringZ:aLund = 0.36");
    pythia.readString("StringZ:bLund = 0.56");
    pythia.readString("StringFlav:probQQtoQ = 0.078");
    pythia.readString("StringFlav:ProbStoUD = 0.2");
    pythia.readString("StringFlav:probQQ1toQQ0join = 0.0275,0.0275,0.0275,0.0275");
    pythia.readString("MultiPartonInteractions:pT0Ref = 2.15");
    pythia.readString("BeamRemnants:remnantMode = 1");
    pythia.readString("BeamRemnants:saturation = 5");

    // Setting the seed here is not sufficient to ensure reproducibility, setting the seed of gRandom is necessary
    pythia.readString("Random:setSeed = on");
    pythia.readString(Form("Random:seed = %d", seed));
    pythia.settings.mode("Beams:idA", 2212);
    pythia.settings.mode("Beams:idB", 2212);
    pythia.settings.parm("Beams:eCM", 14000); // from TeV to GeV
    pythia.init();

    gRandom->SetSeed(seed); // Set the seed to ensure reproducibility of the evevents generated by pythia

    std::string name;
    if (pdg == 421) name = "D^{0}";
    else if (pdg == 411) name = "D^{+}";
    else if (pdg == 413) name = "D*^{+}";
    else {
        printf("Particle %d is not implemented. Exit\n", pdg);
        exit(1);
    }

    std::vector<double> etas = {4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0, 0.9};
    std::map<int, TH1D*> hDmesonRap = {};
    hDmesonRap.insert({9999, new TH1D("hDmesonRap", Form(";#it{y}^{%s};Counts", name.data()), 100, -4.5, 4.5)});
    for (const auto &eta : etas) {
        hDmesonRap.insert({std::round(eta*10), new TH1D(Form("hDmesonRap_EtaLT%d", (int)std::round(eta*10)), Form(";#it{y}^{%s}_{|#eta_{dau trk}|<%.1f};Counts", name.data(), eta), 100, -4.5, 4.5)});
    }

    for (size_t iEvent = 0; iEvent < nEvents; iEvent++) {
        pythia.next();

        // Part 0 is the event, 1 and 2 the beams ==> start from 3
        for (int iPart = 3; iPart < pythia.event.size(); iPart++) {
            auto &part = pythia.event[iPart];

            if (std::abs(part.id()) == pdg) {
                hDmesonRap[9999]->Fill(part.y());
                for (const auto &eta :etas) {
                    if (IsInAcc(part, pythia, eta)) hDmesonRap[(int)std::round(eta*10)]->Fill(part.y());
                }
            }
        }
    }

    TFile *oFile = new TFile(oFileName.data(), "recreate");

    hDmesonRap[9999]->Write();
    for (const auto &eta : etas) {
        hDmesonRap[std::round(eta*10)]->Write();
    }
    oFile->Close();
}
